apiVersion: v1
kind: Service
metadata:
    name: demo-sales-front
spec:
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    selector:
        app: demo-sales-front
    type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: demo-sales-front
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    minReadySeconds: 5
    template:
        metadata:
            labels:
                app: demo-sales-front
        spec:
            containers:
                - name: demo-sales-front
                  image: directone.azurecr.io/directonedemosalesfront_nextjs:latest
                  ports:
                      - containerPort: 80
