FROM node:12-alpine

WORKDIR /usr/app

ENV API="production"
ENV NODE_ENV="production"
ENV PORT="80"

COPY package.json .

COPY . .

RUN npm cache clean --force

RUN npm install
RUN npm install pm2 -g

RUN npm run build

EXPOSE 80

CMD ["npm", "start"]
